const URL_REPO = {
    ROOT: '/',
    LOGIN: '/login',
    REGIST: '/regist',
    SHOW_PROJECT: '/project',
    ADD_PROJECT: '/add_project',
    EDIT_PROJECT: '/edit_project',
    TO_DO_LIST: '/show_task',
    ADD_TASK: '/add_task',
    EDIT_TASK: '/edit_task',
    BE_REGIST: 'http://localhost:8080/api/regist',
    BE_LOGIN: 'http://localhost:8080/api/login',
    BE_ADD_PROJECT: 'http://localhost:8080/api/add_project',
    BE_GET_POINTS: 'http://localhost:8080/api/get_points',
    BE_SHOW_PROJECT: 'http://localhost:8080/api/show_project',
    BE_VOTE_PROJECT: 'http://localhost:8080/api/vote_project',
    BE_EDIT_PROJECT: 'http://localhost:8080/api/edit_project',
    BE_DELETE_PROJECT: 'http://localhost:8080/api/delete_project',
    BE_ADD_TASK: 'http://localhost:8080/api/add_task',
    BE_GET_TASK: 'http://localhost:8080/api/get_task',
    BE_EDIT_TASK: 'http://localhost:8080/api/edit_task',
    BE_USERS: 'http://localhost:8080/api/users',
};

export default  URL_REPO;